# More option see https://github.com/DreamMaoMao/mango/wiki/


source-optional=/home/aj/.config/mango/.env
source=/home/aj/.config/mango/conf/autostart.conf
source=/home/aj/.config/mango/conf/monitors.conf
source=/home/aj/.config/mango/conf/input.conf
source=/home/aj/.config/mango/conf/appearance.conf
source=/home/aj/.config/mango/conf/binds.conf
source=/home/aj/.config/mango/conf/window-tag-rules.conf
source=/home/aj/.config/mango/conf/misc.conf

switchbind=fold,spawn,lockscreen

animations=0

# reload config
bind=CTRL+SHIFT,r,reload_config

# layer rule
# layerrule=animation_type_open:zoom,layer_name:rofi
# layerrule=animation_type_close:zoom,layer_name:rofi
