# Appearance
gappih=0
gappiv=0
gappoh=0
gappov=0
scratchpad_width_ratio=0.8
scratchpad_height_ratio=0.9
borderpx=1

# All colors are in #RRGGBBAA format
rootcolor=0x201b14ff
focuscolor=0xdfc5a4FF
bordercolor=0x444444ff
dropcolor=0xFFdcd7ba
maximizescreencolor=0x89aa61ff
urgentcolor=0xe82424ff

scratchpadcolor=0x516c93ff

globalcolor=0x7e9cd8ff

overlaycolor=0x14a57cff
