exec-once=systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once=wl-paste --watch cliphist store

exec-once=hypridle
exec-once=dunst 
exec-once=waybar
exec-once=swaybg -i ~/.local/share/bg.jpg -m fill

exec-once=kitty
