# exit
bind=SUPER+SHIFT,q,quit
bind=ALT,q,killclient,
bind=ALT,s,togglefloating,
bind=SUPER,m,toggleglobal,
bind=ALT,f,togglefullscreen,
# bind=SUPER+SHIFT,o,toggleoverlay,


bind=SUPER,backspace,spawn,lockscreen
bind=SUPER,n,spawn,dunstctl history-pop
bind=SUPER,8,spawn,togglebar


bind=SUPER,Return,spawn,kitty
bind=SUPER,c,spawn,librewolf
bind=SUPER,e,spawn,nautilus
bind=SUPER,s,spawn,slack

# menu and terminal
bind=Alt,space,spawn,rofi -show drun

bind = ALT, SPACE, spawn, rofi -terminal kitty -show drun 
bind = SUPER+ALT, m, spawn, rofi -show run
bind = SUPER, SPACE, spawn, rofi -show calc -no-show-match -no-sort
bind = SUPER, r, spawn, rofi -show emoji
bind = SUPER, y, spawn, rofi -show ssh
bind = SUPER, v, spawn_shell, cliphist list | rofi -dmenu -display-columns 2 | cliphist decode | wl-copy
bind = SUPER, p, spawn, rofi -theme-str 'element-icon { size: 3ch;}' -combi-modi 'snippets:snippy-snippet rofi' -show combi -modi combi
bind = SUPER, o, spawn, rofi-kpxc



# macOS like screenshots
bind = SUPER + SHIFT, 3, spawn, screenshot
bind = SUPER + SHIFT, 4, spawn, screenshot region
bind = SUPER + SHIFT, y, spawn, zoom

# disable main monitor
bind=SUPER,i,spawn_shell,handle_monitors


# XF86 keybinds
bind=none,XF86AudioRaiseVolume,spawn,sink up
bind=none,XF86AudioLowerVolume,spawn,sink down
bind=none,XF86AudioMute,spawn,sink togglemute
bind=SUPER,q,spawn,sink set

bind=none,XF86AudioMicMute,spawn,sink mic-mute

bind=none,XF86AudioPlay,spawn,playerctl play-pause
bind=none,XF86AudioNext,spawn,playerctl next
bind=none,XF86AudioPrev,spawn,playerctl previous

bind=none,XF86MonBrightnessUp,spawn,backlight monup
bind=none,XF86MonBrightnessDown,spawn,backlight mondown
bind=SUPER,w,spawn,backlight setmon

bind=none,XF86KbdBrightnessUp,spawn,backlight kbdup
bind=none,XF86KbdBrightnessDown,spawn,backlight kbddown


# switch window focus
bind=CTRL,Space,view,-1
bind=ALT,h,focusdir,left
bind=ALT,j,focusdir,down
bind=ALT,k,focusdir,up
bind=ALT,l,focusdir,right

# swap window
bind=SUPER,h,exchange_client,left
bind=SUPER,j,exchange_client,down
bind=SUPER,k,exchange_client,up
bind=SUPER,l,exchange_client,right


# scratchpad
bind=SUPER+ALT,Return,minimized,
bind=SUPER+CTRL+ALT,Return,restore_minimized
bind=ALT,Return,toggle_scratchpad

# switch layout
# bind=SUPER,n,switch_layout

# tag switch
# bind=CTRL+SUPER,Left,viewtoleft,0
bind=CTRL+SUPER,h,viewtoleft_have_client,0
bind=CTRL+SHIFT+SUPER,h,tagtoleft,0           # <- Moves tag to left
# bind=CTRL+SUPER,Right,viewtoright,0
bind=CTRL+SUPER,l,viewtoright_have_client,0
bind=CTRL+SHIFT+SUPER,l,tagtoright,0           # <- Moves tag to right

bind=Ctrl,1,view,1,0
bind=Ctrl,2,view,2,0
bind=Ctrl,3,view,3,0
bind=Ctrl,4,view,4,0
bind=Ctrl,5,view,5,0
bind=Ctrl,6,view,6,0
bind=Ctrl,7,view,7,0
bind=Ctrl,8,view,8,0
bind=Ctrl,9,view,9,0

# tag: move client to the tag and focus it
# tagsilent: move client to the tag and not focus it
# bind=Alt,1,tagsilent,1
bind=CTRL+SHIFT,1,tag,1,synctag
bind=CTRL+SHIFT,2,tag,2,synctag
bind=CTRL+SHIFT,3,tag,3,synctag
bind=CTRL+SHIFT,4,tag,4,synctag
bind=CTRL+SHIFT,5,tag,5,synctag
bind=CTRL+SHIFT,6,tag,6,synctag
bind=CTRL+SHIFT,7,tag,7,synctag
bind=CTRL+SHIFT,8,tag,8,synctag
bind=CTRL+SHIFT,9,tag,9,synctag

# monitor switch
bind=alt+shift,h,focusmon,left
bind=alt+shift,l,focusmon,right
bind=SUPER+Alt,h,tagmon,left
bind=SUPER+Alt,l,tagmon,right

mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize


# Axis Bindings
# axisbind=SUPER,UP,viewtoleft_have_client
# axisbind=SUPER,DOWN,viewtoright_have_client


