# keyboard
repeat_rate=70
repeat_delay=250
numlockon=0
xkb_rules_options=caps:escape,shift:both_capslock

cursor_hide_timeout=2
sloppyfocus=1
focus_on_activate=1
warpcursor=1

# Trackpad
# need relogin to make it apply
trackpad_natural_scrolling=1
disable_while_typing=1
trackpad_accel_speed=0.25
trackpad_scroll_factor=1.5

# mouse
# need relogin to make it apply
mouse_natural_scrolling=0

cursor_size=30
cursor_theme=vimix-kanagawa-cursors-lotus
