monitorrule=name:eDP-1,scale:2,x:0,y:0
monitorrule=name:DP-8,scale:1,x:1920,y:0
monitorrule=name:DP-7,scale:1,x:4480,y:0
monitorrule=name:DP-10,scale:1,x:1920,y:0
monitorrule=name:DP-9,scale:1,x:4480,y:0
