windowrule=isfloating:1,isfullscreen:1,title:wayland-boomer
windowrule=isterm:1,title:kitty

windowrule=tags:1,title:.*Slack.*
windowrule=tags:1,isfloating:1,isglobal:1,title:Huddle.*

windowrule=tags:1,title:.*Thunderbird.*

windowrule=isfloating:1,title:QjackCtl
windowrule=isfloating:1,title:Graph.*

windowrule=isfloating:1,title:^(default) Active.*
tagrule=id:1,layout_name:fair
tagrule=id:2,layout_name:fair
tagrule=id:3,layout_name:fair
tagrule=id:4,layout_name:fair
tagrule=id:5,layout_name:fair
tagrule=id:6,layout_name:fair
tagrule=id:7,layout_name:fair
tagrule=id:8,layout_name:fair
tagrule=id:9,layout_name:fair
