#!/bin/bash
## ~/.config/lf/previewer_sandbox

set -euo pipefail
(
    exec bwrap \
     --ro-bind /usr/bin /usr/bin \
     --ro-bind /usr/share/ /usr/share/ \
     --ro-bind /usr/lib /usr/lib \
     --ro-bind /usr/lib64 /usr/lib64 \
     --symlink /usr/bin /bin \
     --symlink /usr/bin /sbin \
     --symlink /usr/lib /lib \
     --symlink /usr/lib64 /lib64 \
     --proc /proc \
     --uid "$(id -u)" --gid "$(id -g)" \
     --dev /dev  \
     --dev-bind /dev/tty /dev/tty \
     --ro-bind /etc /etc \
     --ro-bind "$HOME/.local/bin" "$HOME/.local/bin" \
     --ro-bind ~/.config ~/.config \
     --ro-bind ~/.cache ~/.cache \
     --ro-bind "$PWD" "$PWD" \
     --unshare-all \
     --new-session \
     bash ~/.config/lf/previewer "$@"
)
