#!/bin/sh

# Merge all copy buffers
autocutsel -selection PRIMARY -fork

# Set brightness
sudo brillo -S 15
# sudo brillo -S 0 -k

# Set volume
pactl set-sink-volume @DEFAULT_SINK@ 75%

source $HOME/.config/setup
# start plasma
export DESKTOP_SESSION=plasma
exec startplasma-wayland
