#! /bin/sh

xsetroot -bg "#000000"

source ~/.dotfiles/scheme

bspc config normal_border_color $black1
bspc config focused_border_color $black2

picom -b --experimental-backend

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config focus_follows_pointer true

bspc config border_width            1
bspc config window_gap              10 
bspc config -m "^1" top_padding     40

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc rule -a Zathura state=tiled layer=above
bspc rule -a rofi state=floating center=on private=on layer=above

pgrep bspswallow || bspswallow &

~/.dotfiles/wmstuff
